version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install sphinx
    - sphinx-apidoc -o docs/ --separate --no-toc -f cid

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

formats:
  - epub
  - htmlzip
