from typing import overload

from typing_extensions import TypeAlias

# Type aliases
CID: TypeAlias = CIDv0 | CIDv1

class BaseCID:
    @property
    def codec(self) -> str: ...
    @property
    def multihash(self) -> bytes: ...
    @property
    def version(self) -> int: ...
    @property
    def buffer(self) -> bytes: ...
    def encode(self, encoding: str | None = None) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CIDv0(BaseCID):
    CODEC: str

    def __init__(self, multihash: str | bytes) -> None: ...
    def to_v1(self) -> CIDv1: ...

class CIDv1(BaseCID):
    def __init__(self, codec: str, multihash: str | bytes) -> None: ...
    def to_v0(self) -> CIDv0: ...

# Function overloads for make_cid
@overload
def make_cid(base58_encoded_multihash: str) -> CIDv0: ...
@overload
def make_cid(multihash: str | bytes) -> CIDv0: ...
@overload
def make_cid(multibase_encoded_multihash: str | bytes) -> CIDv1: ...
@overload
def make_cid(version: int, codec: str, multihash: str | bytes) -> CIDv1: ...
@overload
def make_cid(*args: str | bytes | int) -> CID: ...
def from_bytes(cidbytes: bytes) -> CID: ...
def from_string(cidstring: str) -> CID: ...
def is_cid(cidstring: str | bytes) -> bool: ...
